import type { Tool, Category, Testimonial } from "@/types"

export const categories: Category[] = [
  {
    id: "pdf",
    name: "PDF Tools",
    description: "Convert, merge, split, compress and edit PDFs",
    icon: "FileText",
    color: "#ef4444",
    toolCount: 24,
  },
  {
    id: "image",
    name: "Image Tools",
    description: "Edit, convert, compress and enhance images",
    icon: "Image",
    color: "#f59e0b",
    toolCount: 22,
  },
  {
    id: "document",
    name: "Document Tools",
    description: "Edit, format and convert documents",
    icon: "File",
    color: "#3b82f6",
    toolCount: 18,
  },
  {
    id: "developer",
    name: "Developer Tools",
    description: "Code formatters, generators, and dev utilities",
    icon: "Code",
    color: "#8b5cf6",
    toolCount: 38,
  },
  {
    id: "video",
    name: "Video Tools",
    description: "Trim, merge, compress and convert videos",
    icon: "Video",
    color: "#10b981",
    toolCount: 10,
  },
  {
    id: "audio",
    name: "Audio Tools",
    description: "Edit, cut, merge and convert audio files",
    icon: "Music",
    color: "#ec4899",
    toolCount: 6,
  },
  {
    id: "business",
    name: "Business Tools",
    description: "Invoices, resumes, certificates and more",
    icon: "Briefcase",
    color: "#14b8a6",
    toolCount: 14,
  },
  {
    id: "office",
    name: "Office Tools",
    description: "Calendar, notes, calculator and productivity tools",
    icon: "Building2",
    color: "#6b7280",
    toolCount: 18,
  },
  {
    id: "ai",
    name: "AI Tools",
    description: "AI writing, chat, code generation and analysis",
    icon: "Sparkles",
    color: "#f97316",
    toolCount: 20,
  },
  {
    id: "security",
    name: "Security Tools",
    description: "Password manager, encryption, and security checks",
    icon: "Shield",
    color: "#06b6d4",
    toolCount: 7,
  },
  {
    id: "utility",
    name: "Utility Tools",
    description: "File management, converters, and daily utilities",
    icon: "Wrench",
    color: "#78716c",
    toolCount: 9,
  },
]

export const tools: Tool[] = [
  // PDF Tools
  { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF documents to editable Word files", icon: "FileText", category: "pdf", slug: "pdf-to-word", isPopular: true, color: "#ef4444" },
  { id: "word-to-pdf", name: "Word to PDF", description: "Convert Word documents to PDF format", icon: "FileText", category: "pdf", slug: "word-to-pdf", isPopular: true, color: "#ef4444" },
  { id: "pdf-to-excel", name: "PDF to Excel", description: "Extract tables from PDFs to Excel spreadsheets", icon: "Table", category: "pdf", slug: "pdf-to-excel", color: "#ef4444" },
  { id: "excel-to-pdf", name: "Excel to PDF", description: "Convert Excel spreadsheets to PDF", icon: "Table", category: "pdf", slug: "excel-to-pdf", color: "#ef4444" },
  { id: "pdf-to-ppt", name: "PDF to PPT", description: "Convert PDF files to PowerPoint presentations", icon: "Presentation", category: "pdf", slug: "pdf-to-ppt", color: "#ef4444" },
  { id: "ppt-to-pdf", name: "PPT to PDF", description: "Convert PowerPoint presentations to PDF", icon: "Presentation", category: "pdf", slug: "ppt-to-pdf", color: "#ef4444" },
  { id: "merge-pdf", name: "Merge PDF", description: "Combine multiple PDF files into one", icon: "Files", category: "pdf", slug: "merge-pdf", isPopular: true, color: "#ef4444" },
  { id: "split-pdf", name: "Split PDF", description: "Split PDF files into separate documents", icon: "Scissors", category: "pdf", slug: "split-pdf", isPopular: true, color: "#ef4444" },
  { id: "compress-pdf", name: "Compress PDF", description: "Reduce PDF file size without quality loss", icon: "FileDown", category: "pdf", slug: "compress-pdf", isPopular: true, color: "#ef4444" },
  { id: "rotate-pdf", name: "Rotate PDF", description: "Rotate pages in your PDF documents", icon: "RotateCw", category: "pdf", slug: "rotate-pdf", color: "#ef4444" },
  { id: "unlock-pdf", name: "Unlock PDF", description: "Remove password protection from PDFs", icon: "Unlock", category: "pdf", slug: "unlock-pdf", color: "#ef4444" },
  { id: "lock-pdf", name: "Lock PDF", description: "Add password protection to your PDFs", icon: "Lock", category: "pdf", slug: "lock-pdf", color: "#ef4444" },
  { id: "watermark-pdf", name: "Watermark PDF", description: "Add watermarks to your PDF documents", icon: "Droplets", category: "pdf", slug: "watermark-pdf", color: "#ef4444" },
  { id: "sign-pdf", name: "Sign PDF", description: "Add digital signatures to PDFs", icon: "Signature", category: "pdf", slug: "sign-pdf", color: "#ef4444" },
  { id: "ocr-pdf", name: "OCR PDF", description: "Extract text from scanned PDFs", icon: "Scan", category: "pdf", slug: "ocr-pdf", isNew: true, color: "#ef4444" },
  { id: "extract-images-pdf", name: "Extract Images", description: "Extract images from PDF files", icon: "ImageDown", category: "pdf", slug: "extract-images-pdf", color: "#ef4444" },
  { id: "extract-text-pdf", name: "Extract Text", description: "Extract text content from PDFs", icon: "Text", category: "pdf", slug: "extract-text-pdf", color: "#ef4444" },
  { id: "delete-pages", name: "Delete Pages", description: "Remove unwanted pages from PDFs", icon: "Trash2", category: "pdf", slug: "delete-pages", color: "#ef4444" },
  { id: "reorder-pages", name: "Reorder Pages", description: "Rearrange pages in your PDF document", icon: "ArrowUpDown", category: "pdf", slug: "reorder-pages", color: "#ef4444" },
  { id: "crop-pdf", name: "Crop PDF", description: "Crop PDF pages to custom dimensions", icon: "Crop", category: "pdf", slug: "crop-pdf", color: "#ef4444" },
  { id: "images-to-pdf", name: "Images to PDF", description: "Convert multiple images to PDF", icon: "Images", category: "pdf", slug: "images-to-pdf", isPopular: true, color: "#ef4444" },
  { id: "html-to-pdf", name: "HTML to PDF", description: "Convert HTML files to PDF format", icon: "FileCode", category: "pdf", slug: "html-to-pdf", color: "#ef4444" },
  { id: "pdf-to-jpg", name: "PDF to JPG", description: "Convert PDF pages to JPG images", icon: "FileImage", category: "pdf", slug: "pdf-to-jpg", color: "#ef4444" },
  { id: "jpg-to-pdf", name: "JPG to PDF", description: "Convert JPG images to PDF", icon: "FileImage", category: "pdf", slug: "jpg-to-pdf", isPopular: true, color: "#ef4444" },

  // Image Tools
  { id: "background-remover", name: "Background Remover", description: "Remove image backgrounds automatically", icon: "ImageOff", category: "image", slug: "background-remover", isPopular: true, isPro: false, color: "#f59e0b" },
  { id: "image-compressor", name: "Image Compressor", description: "Compress images without losing quality", icon: "FileDown", category: "image", slug: "image-compressor", isPopular: true, color: "#f59e0b" },
  { id: "image-upscaler", name: "Image Upscaler", description: "Upscale images with AI enhancement", icon: "ZoomIn", category: "image", slug: "image-upscaler", isPro: false, color: "#f59e0b" },
  { id: "resize-image", name: "Resize Image", description: "Resize images to exact dimensions", icon: "Maximize", category: "image", slug: "resize-image", isPopular: true, color: "#f59e0b" },
  { id: "crop-image", name: "Crop Image", description: "Crop images to any aspect ratio", icon: "Crop", category: "image", slug: "crop-image", color: "#f59e0b" },
  { id: "rotate-image", name: "Rotate Image", description: "Rotate images by any angle", icon: "RotateCw", category: "image", slug: "rotate-image", color: "#f59e0b" },
  { id: "flip-image", name: "Flip Image", description: "Flip images horizontally or vertically", icon: "FlipHorizontal", category: "image", slug: "flip-image", color: "#f59e0b" },
  { id: "blur-background", name: "Blur Background", description: "Blur image backgrounds with precision", icon: "Blur", category: "image", slug: "blur-background", color: "#f59e0b" },
  { id: "ai-enhance", name: "AI Enhance", description: "Enhance image quality with AI", icon: "Sparkles", category: "image", slug: "ai-enhance", isPro: false, color: "#f59e0b" },
  { id: "image-to-png", name: "Image to PNG", description: "Convert any image format to PNG", icon: "FileImage", category: "image", slug: "image-to-png", isPopular: true, color: "#f59e0b" },
  { id: "png-to-jpg", name: "PNG to JPG", description: "Convert PNG images to JPG format", icon: "FileImage", category: "image", slug: "png-to-jpg", color: "#f59e0b" },
  { id: "jpg-to-webp", name: "JPG to WebP", description: "Convert JPG to modern WebP format", icon: "FileImage", category: "image", slug: "jpg-to-webp", color: "#f59e0b" },
  { id: "webp-converter", name: "WebP Converter", description: "Convert images to and from WebP", icon: "Repeat", category: "image", slug: "webp-converter", color: "#f59e0b" },
  { id: "svg-converter", name: "SVG Converter", description: "Convert images to SVG format", icon: "FileImage", category: "image", slug: "svg-converter", color: "#f59e0b" },
  { id: "heic-converter", name: "HEIC Converter", description: "Convert HEIC images to standard formats", icon: "FileImage", category: "image", slug: "heic-converter", color: "#f59e0b" },
  { id: "ico-generator", name: "ICO Generator", description: "Generate favicon ICO files", icon: "FileImage", category: "image", slug: "ico-generator", color: "#f59e0b" },
  { id: "qr-generator", name: "QR Generator", description: "Generate QR codes instantly", icon: "QrCode", category: "image", slug: "qr-generator", isPopular: true, color: "#f59e0b" },
  { id: "barcode-generator", name: "Barcode Generator", description: "Generate barcodes for products", icon: "Barcode", category: "image", slug: "barcode-generator", color: "#f59e0b" },
  { id: "watermark-image", name: "Watermark Images", description: "Add watermarks to your images", icon: "Droplets", category: "image", slug: "watermark-image", color: "#f59e0b" },
  { id: "meme-generator", name: "Meme Generator", description: "Create funny memes with custom text", icon: "Smile", category: "image", slug: "meme-generator", color: "#f59e0b" },
  { id: "screenshot-editor", name: "Screenshot Editor", description: "Edit and annotate screenshots", icon: "Monitor", category: "image", slug: "screenshot-editor", color: "#f59e0b" },
  { id: "collage-maker", name: "Collage Maker", description: "Create beautiful photo collages", icon: "Layout", category: "image", slug: "collage-maker", color: "#f59e0b" },

  // Document Tools
  { id: "word-editor", name: "Word Editor", description: "Edit Word documents online", icon: "FileEdit", category: "document", slug: "word-editor", color: "#3b82f6" },
  { id: "markdown-editor", name: "Markdown Editor", description: "Write and preview Markdown documents", icon: "FileEdit", category: "document", slug: "markdown-editor", isPopular: true, color: "#3b82f6" },
  { id: "rich-text-editor", name: "Rich Text Editor", description: "Format documents with rich text tools", icon: "FileEdit", category: "document", slug: "rich-text-editor", color: "#3b82f6" },
  { id: "text-compare", name: "Text Compare", description: "Compare two text documents side by side", icon: "FileDiff", category: "document", slug: "text-compare", isPopular: true, color: "#3b82f6" },
  { id: "find-duplicates", name: "Find Duplicate Lines", description: "Find duplicate lines in text", icon: "Search", category: "document", slug: "find-duplicates", color: "#3b82f6" },
  { id: "remove-duplicates", name: "Remove Duplicate Lines", description: "Remove duplicate lines from text", icon: "Filter", category: "document", slug: "remove-duplicates", color: "#3b82f6" },
  { id: "word-counter", name: "Word Counter", description: "Count words, characters, and paragraphs", icon: "Hash", category: "document", slug: "word-counter", isPopular: true, color: "#3b82f6" },
  { id: "character-counter", name: "Character Counter", description: "Count characters with and without spaces", icon: "Hash", category: "document", slug: "character-counter", color: "#3b82f6" },
  { id: "case-converter", name: "Case Converter", description: "Convert text between uppercase, lowercase, and more", icon: "CaseSensitive", category: "document", slug: "case-converter", isPopular: true, color: "#3b82f6" },
  { id: "text-cleaner", name: "Text Cleaner", description: "Clean and format text content", icon: "SprayCan", category: "document", slug: "text-cleaner", color: "#3b82f6" },
  { id: "remove-blank-lines", name: "Remove Blank Lines", description: "Remove empty lines from text", icon: "RemoveFormatting", category: "document", slug: "remove-blank-lines", color: "#3b82f6" },
  { id: "json-formatter", name: "JSON Formatter", description: "Format and beautify JSON data", icon: "Braces", category: "document", slug: "json-formatter", isPopular: true, color: "#3b82f6" },
  { id: "json-validator", name: "JSON Validator", description: "Validate JSON data syntax", icon: "CheckCircle", category: "document", slug: "json-validator", color: "#3b82f6" },
  { id: "yaml-formatter", name: "YAML Formatter", description: "Format and validate YAML files", icon: "Braces", category: "document", slug: "yaml-formatter", color: "#3b82f6" },
  { id: "xml-formatter", name: "XML Formatter", description: "Format and beautify XML data", icon: "Braces", category: "document", slug: "xml-formatter", color: "#3b82f6" },
  { id: "csv-viewer", name: "CSV Viewer", description: "View and analyze CSV files", icon: "Table", category: "document", slug: "csv-viewer", color: "#3b82f6" },
  { id: "csv-to-json", name: "CSV to JSON", description: "Convert CSV data to JSON format", icon: "Table", category: "document", slug: "csv-to-json", color: "#3b82f6" },
  { id: "json-to-csv", name: "JSON to CSV", description: "Convert JSON data to CSV format", icon: "Table", category: "document", slug: "json-to-csv", color: "#3b82f6" },

  // Developer Tools
  { id: "base64-encode", name: "Base64 Encode", description: "Encode text to Base64", icon: "Code", category: "developer", slug: "base64-encode", color: "#8b5cf6" },
  { id: "base64-decode", name: "Base64 Decode", description: "Decode Base64 to text", icon: "Code", category: "developer", slug: "base64-decode", color: "#8b5cf6" },
  { id: "jwt-decoder", name: "JWT Decoder", description: "Decode and inspect JWT tokens", icon: "Key", category: "developer", slug: "jwt-decoder", isPopular: true, color: "#8b5cf6" },
  { id: "jwt-generator", name: "JWT Generator", description: "Generate JWT tokens", icon: "Key", category: "developer", slug: "jwt-generator", color: "#8b5cf6" },
  { id: "uuid-generator", name: "UUID Generator", description: "Generate UUID v4 identifiers", icon: "Fingerprint", category: "developer", slug: "uuid-generator", isPopular: true, color: "#8b5cf6" },
  { id: "hash-generator", name: "Hash Generator", description: "Generate MD5, SHA256, bcrypt hashes", icon: "Hash", category: "developer", slug: "hash-generator", isPopular: true, color: "#8b5cf6" },
  { id: "md5-generator", name: "MD5 Generator", description: "Generate MD5 hashes", icon: "Hash", category: "developer", slug: "md5-generator", color: "#8b5cf6" },
  { id: "sha256-generator", name: "SHA256 Generator", description: "Generate SHA256 hashes", icon: "Hash", category: "developer", slug: "sha256-generator", color: "#8b5cf6" },
  { id: "bcrypt-generator", name: "bcrypt Generator", description: "Generate bcrypt hashes", icon: "Hash", category: "developer", slug: "bcrypt-generator", color: "#8b5cf6" },
  { id: "regex-tester", name: "Regex Tester", description: "Test regular expressions in real-time", icon: "Regex", category: "developer", slug: "regex-tester", isPopular: true, color: "#8b5cf6" },
  { id: "url-encoder", name: "URL Encoder", description: "Encode text for URL usage", icon: "Link", category: "developer", slug: "url-encoder", color: "#8b5cf6" },
  { id: "url-decoder", name: "URL Decoder", description: "Decode URL-encoded text", icon: "Link", category: "developer", slug: "url-decoder", color: "#8b5cf6" },
  { id: "html-encoder", name: "HTML Encoder", description: "Encode HTML entities", icon: "Code2", category: "developer", slug: "html-encoder", color: "#8b5cf6" },
  { id: "html-decoder", name: "HTML Decoder", description: "Decode HTML entities", icon: "Code2", category: "developer", slug: "html-decoder", color: "#8b5cf6" },
  { id: "sql-formatter", name: "SQL Formatter", description: "Format SQL queries beautifully", icon: "Database", category: "developer", slug: "sql-formatter", color: "#8b5cf6" },
  { id: "prettier", name: "Prettier Formatter", description: "Format code with Prettier", icon: "Code2", category: "developer", slug: "prettier", color: "#8b5cf6" },
  { id: "minify-html", name: "Minify HTML", description: "Minify HTML code", icon: "Compress", category: "developer", slug: "minify-html", color: "#8b5cf6" },
  { id: "minify-css", name: "Minify CSS", description: "Minify CSS code", icon: "Compress", category: "developer", slug: "minify-css", color: "#8b5cf6" },
  { id: "minify-js", name: "Minify JS", description: "Minify JavaScript code", icon: "Compress", category: "developer", slug: "minify-js", color: "#8b5cf6" },
  { id: "beautify", name: "Beautify Code", description: "Beautify and format source code", icon: "Sparkles", category: "developer", slug: "beautify", color: "#8b5cf6" },
  { id: "color-picker", name: "Color Picker", description: "Pick and convert colors between formats", icon: "Palette", category: "developer", slug: "color-picker", isPopular: true, color: "#8b5cf6" },
  { id: "gradient-generator", name: "Gradient Generator", description: "Create beautiful CSS gradients", icon: "Gradient", category: "developer", slug: "gradient-generator", color: "#8b5cf6" },
  { id: "css-generator", name: "CSS Generator", description: "Generate CSS code visually", icon: "FileCode", category: "developer", slug: "css-generator", color: "#8b5cf6" },
  { id: "flexbox-generator", name: "Flexbox Generator", description: "Visual Flexbox layout generator", icon: "Columns3", category: "developer", slug: "flexbox-generator", color: "#8b5cf6" },
  { id: "grid-generator", name: "Grid Generator", description: "Visual CSS Grid layout generator", icon: "LayoutGrid", category: "developer", slug: "grid-generator", color: "#8b5cf6" },
  { id: "cron-generator", name: "Cron Generator", description: "Generate cron expressions", icon: "Clock", category: "developer", slug: "cron-generator", color: "#8b5cf6" },
  { id: "timestamp-converter", name: "Timestamp Converter", description: "Convert Unix timestamps to dates", icon: "Clock", category: "developer", slug: "timestamp-converter", isPopular: true, color: "#8b5cf6" },
  { id: "unix-time", name: "Unix Time", description: "Current Unix timestamp and converter", icon: "Clock", category: "developer", slug: "unix-time", color: "#8b5cf6" },
  { id: "lorem-ipsum", name: "Lorem Ipsum", description: "Generate placeholder text", icon: "TextQuote", category: "developer", slug: "lorem-ipsum", color: "#8b5cf6" },
  { id: "password-generator", name: "Password Generator", description: "Generate strong passwords", icon: "Key", category: "developer", slug: "password-generator", isPopular: true, color: "#8b5cf6" },
  { id: "random-generator", name: "Random Generator", description: "Generate random numbers and strings", icon: "Shuffle", category: "developer", slug: "random-generator", color: "#8b5cf6" },
  { id: "slug-generator", name: "Slug Generator", description: "Generate URL-friendly slugs", icon: "Link", category: "developer", slug: "slug-generator", color: "#8b5cf6" },
  { id: "diff-checker", name: "Diff Checker", description: "Compare text differences", icon: "FileDiff", category: "developer", slug: "diff-checker", isPopular: true, color: "#8b5cf6" },
  { id: "api-tester", name: "API Tester", description: "Test REST API endpoints", icon: "Globe", category: "developer", slug: "api-tester", isNew: true, color: "#8b5cf6" },
  { id: "rest-client", name: "REST Client", description: "Make HTTP requests to APIs", icon: "Globe", category: "developer", slug: "rest-client", color: "#8b5cf6" },
  { id: "graphql-playground", name: "GraphQL Playground", description: "Test GraphQL queries", icon: "Globe", category: "developer", slug: "graphql-playground", isNew: true, color: "#8b5cf6" },
  { id: "webhook-tester", name: "Webhook Tester", description: "Test and debug webhooks", icon: "Webhook", category: "developer", slug: "webhook-tester", color: "#8b5cf6" },
  { id: "curl-generator", name: "Curl Generator", description: "Generate curl commands", icon: "Terminal", category: "developer", slug: "curl-generator", color: "#8b5cf6" },

  // Video Tools
  { id: "video-compressor", name: "Video Compressor", description: "Compress video files", icon: "FileDown", category: "video", slug: "video-compressor", color: "#10b981" },
  { id: "trim-video", name: "Trim Video", description: "Trim and cut video segments", icon: "Scissors", category: "video", slug: "trim-video", isPopular: true, color: "#10b981" },
  { id: "merge-videos", name: "Merge Videos", description: "Combine multiple videos into one", icon: "Files", category: "video", slug: "merge-videos", color: "#10b981" },
  { id: "extract-audio", name: "Extract Audio", description: "Extract audio from video files", icon: "Music", category: "video", slug: "extract-audio", color: "#10b981" },
  { id: "video-to-gif", name: "Video to GIF", description: "Convert video clips to GIFs", icon: "FileImage", category: "video", slug: "video-to-gif", isPopular: true, color: "#10b981" },
  { id: "gif-to-mp4", name: "GIF to MP4", description: "Convert GIF animations to MP4", icon: "FileVideo", category: "video", slug: "gif-to-mp4", color: "#10b981" },
  { id: "add-watermark-video", name: "Add Watermark", description: "Add watermarks to videos", icon: "Droplets", category: "video", slug: "add-watermark-video", color: "#10b981" },
  { id: "mute-video", name: "Mute Video", description: "Remove audio from video", icon: "VolumeX", category: "video", slug: "mute-video", color: "#10b981" },
  { id: "rotate-video", name: "Rotate Video", description: "Rotate video orientation", icon: "RotateCw", category: "video", slug: "rotate-video", color: "#10b981" },
  { id: "resize-video", name: "Resize Video", description: "Resize video dimensions", icon: "Maximize", category: "video", slug: "resize-video", color: "#10b981" },

  // Audio Tools
  { id: "mp3-converter", name: "MP3 Converter", description: "Convert audio to MP3 format", icon: "FileAudio", category: "audio", slug: "mp3-converter", isPopular: true, color: "#ec4899" },
  { id: "audio-cutter", name: "Audio Cutter", description: "Cut and trim audio files", icon: "Scissors", category: "audio", slug: "audio-cutter", color: "#ec4899" },
  { id: "merge-audio", name: "Merge Audio", description: "Combine multiple audio files", icon: "Files", category: "audio", slug: "merge-audio", color: "#ec4899" },
  { id: "volume-booster", name: "Volume Booster", description: "Increase audio volume", icon: "Volume2", category: "audio", slug: "volume-booster", color: "#ec4899" },
  { id: "noise-remover", name: "Noise Remover", description: "Remove background noise from audio", icon: "EarOff", category: "audio", slug: "noise-remover", isPro: false, color: "#ec4899" },
  { id: "voice-recorder", name: "Voice Recorder", description: "Record audio directly in browser", icon: "Mic", category: "audio", slug: "voice-recorder", color: "#ec4899" },

  // Business Tools
  { id: "invoice-generator", name: "Invoice Generator", description: "Create professional invoices", icon: "FileText", category: "business", slug: "invoice-generator", isPopular: true, color: "#14b8a6" },
  { id: "quotation-generator", name: "Quotation Generator", description: "Create business quotations", icon: "FileText", category: "business", slug: "quotation-generator", color: "#14b8a6" },
  { id: "receipt-generator", name: "Receipt Generator", description: "Generate receipts instantly", icon: "Receipt", category: "business", slug: "receipt-generator", color: "#14b8a6" },
  { id: "resume-builder", name: "Resume Builder", description: "Build professional resumes", icon: "FileUser", category: "business", slug: "resume-builder", isPopular: true, isPro: false, color: "#14b8a6" },
  { id: "cv-builder", name: "CV Builder", description: "Create comprehensive CVs", icon: "FileUser", category: "business", slug: "cv-builder", color: "#14b8a6" },
  { id: "cover-letter-builder", name: "Cover Letter Builder", description: "Write professional cover letters", icon: "FileEdit", category: "business", slug: "cover-letter-builder", color: "#14b8a6" },
  { id: "business-card-maker", name: "Business Card Maker", description: "Design business cards", icon: "IdCard", category: "business", slug: "business-card-maker", color: "#14b8a6" },
  { id: "email-signature", name: "Email Signature Generator", description: "Create email signatures", icon: "Mail", category: "business", slug: "email-signature", color: "#14b8a6" },
  { id: "qr-business-card", name: "QR Business Card", description: "Digital business cards with QR", icon: "QrCode", category: "business", slug: "qr-business-card", color: "#14b8a6" },
  { id: "id-card-generator", name: "ID Card Generator", description: "Generate ID cards", icon: "IdCard", category: "business", slug: "id-card-generator", color: "#14b8a6" },
  { id: "certificate-generator", name: "Certificate Generator", description: "Create certificates", icon: "Award", category: "business", slug: "certificate-generator", color: "#14b8a6" },
  { id: "payslip-generator", name: "Payslip Generator", description: "Generate employee payslips", icon: "FileText", category: "business", slug: "payslip-generator", color: "#14b8a6" },
  { id: "letter-generator", name: "Letter Generator", description: "Write formal letters", icon: "FileEdit", category: "business", slug: "letter-generator", color: "#14b8a6" },

  // Office Tools
  { id: "excel-viewer", name: "Excel Viewer", description: "View Excel spreadsheets online", icon: "Table", category: "office", slug: "excel-viewer", color: "#6b7280" },
  { id: "word-viewer", name: "Word Viewer", description: "View Word documents online", icon: "FileText", category: "office", slug: "word-viewer", color: "#6b7280" },
  { id: "ppt-viewer", name: "PowerPoint Viewer", description: "View PowerPoint presentations", icon: "Presentation", category: "office", slug: "ppt-viewer", color: "#6b7280" },
  { id: "spreadsheet-editor", name: "Spreadsheet Editor", description: "Edit spreadsheets online", icon: "Table", category: "office", slug: "spreadsheet-editor", color: "#6b7280" },
  { id: "presentation-viewer", name: "Presentation Viewer", description: "View presentation files", icon: "Presentation", category: "office", slug: "presentation-viewer", color: "#6b7280" },
  { id: "calendar", name: "Calendar", description: "Manage your schedule", icon: "Calendar", category: "office", slug: "calendar", color: "#6b7280" },
  { id: "notes", name: "Notes", description: "Take and manage notes", icon: "StickyNote", category: "office", slug: "notes", isPopular: true, color: "#6b7280" },
  { id: "task-manager", name: "Task Manager", description: "Manage your tasks", icon: "CheckSquare", category: "office", slug: "task-manager", isPopular: true, color: "#6b7280" },
  { id: "todo", name: "Todo List", description: "Simple todo list manager", icon: "CheckSquare", category: "office", slug: "todo", color: "#6b7280" },
  { id: "pomodoro", name: "Pomodoro Timer", description: "Focus with Pomodoro technique", icon: "Timer", category: "office", slug: "pomodoro", isPopular: true, color: "#6b7280" },
  { id: "calculator", name: "Calculator", description: "Basic and scientific calculator", icon: "Calculator", category: "office", slug: "calculator", isPopular: true, color: "#6b7280" },
  { id: "unit-converter", name: "Unit Converter", description: "Convert between measurement units", icon: "ArrowLeftRight", category: "office", slug: "unit-converter", color: "#6b7280" },
  { id: "currency-converter", name: "Currency Converter", description: "Convert currencies in real-time", icon: "DollarSign", category: "office", slug: "currency-converter", isPopular: true, color: "#6b7280" },
  { id: "timezone-converter", name: "Timezone Converter", description: "Convert time across timezones", icon: "Globe", category: "office", slug: "timezone-converter", color: "#6b7280" },
  { id: "age-calculator", name: "Age Calculator", description: "Calculate exact age", icon: "Calendar", category: "office", slug: "age-calculator", color: "#6b7280" },
  { id: "emi-calculator", name: "EMI Calculator", description: "Calculate loan EMIs", icon: "Calculator", category: "office", slug: "emi-calculator", color: "#6b7280" },
  { id: "percentage-calculator", name: "Percentage Calculator", description: "Calculate percentages easily", icon: "Percent", category: "office", slug: "percentage-calculator", color: "#6b7280" },
  { id: "gst-calculator", name: "GST Calculator", description: "Calculate GST amounts", icon: "Calculator", category: "office", slug: "gst-calculator", color: "#6b7280" },
  { id: "bmi-calculator", name: "BMI Calculator", description: "Calculate body mass index", icon: "Calculator", category: "office", slug: "bmi-calculator", color: "#6b7280" },
  { id: "scientific-calculator", name: "Scientific Calculator", description: "Advanced scientific calculator", icon: "Calculator", category: "office", slug: "scientific-calculator", color: "#6b7280" },

  // AI Tools
  { id: "ai-chat", name: "AI Chat", description: "Chat with AI assistant", icon: "MessageSquare", category: "ai", slug: "ai-chat", isPopular: true, color: "#f97316" },
  { id: "ai-writer", name: "AI Writer", description: "Write content with AI", icon: "Pen", category: "ai", slug: "ai-writer", isPopular: true, color: "#f97316" },
  { id: "ai-summarizer", name: "AI Summarizer", description: "Summarize text with AI", icon: "FileText", category: "ai", slug: "ai-summarizer", color: "#f97316" },
  { id: "grammar-fixer", name: "Grammar Fixer", description: "Fix grammar and spelling", icon: "SpellCheck", category: "ai", slug: "grammar-fixer", isPopular: true, color: "#f97316" },
  { id: "paraphraser", name: "Paraphraser", description: "Rewrite text with AI", icon: "Repeat", category: "ai", slug: "paraphraser", color: "#f97316" },
  { id: "translator", name: "Translator", description: "Translate text between languages", icon: "Languages", category: "ai", slug: "translator", isPopular: true, color: "#f97316" },
  { id: "email-writer", name: "Email Writer", description: "Write emails with AI", icon: "Mail", category: "ai", slug: "email-writer", color: "#f97316" },
  { id: "blog-writer", name: "Blog Writer", description: "Write blog posts with AI", icon: "FileEdit", category: "ai", slug: "blog-writer", color: "#f97316" },
  { id: "code-generator", name: "Code Generator", description: "Generate code with AI", icon: "Code", category: "ai", slug: "code-generator", isPopular: true, color: "#f97316" },
  { id: "code-explainer", name: "Code Explainer", description: "Explain code with AI", icon: "Code2", category: "ai", slug: "code-explainer", color: "#f97316" },
  { id: "bug-fixer", name: "Bug Fixer", description: "Fix bugs with AI assistance", icon: "Bug", category: "ai", slug: "bug-fixer", color: "#f97316" },
  { id: "prompt-generator", name: "Prompt Generator", description: "Generate AI prompts", icon: "Sparkles", category: "ai", slug: "prompt-generator", color: "#f97316" },
  { id: "prompt-improver", name: "Prompt Improver", description: "Improve your AI prompts", icon: "Sparkles", category: "ai", slug: "prompt-improver", color: "#f97316" },
  { id: "resume-ai", name: "Resume AI", description: "Optimize resume with AI", icon: "FileUser", category: "ai", slug: "resume-ai", isPro: false, color: "#f97316" },
  { id: "cover-letter-ai", name: "Cover Letter AI", description: "Write cover letters with AI", icon: "FileEdit", category: "ai", slug: "cover-letter-ai", color: "#f97316" },
  { id: "meeting-notes", name: "Meeting Notes", description: "Generate meeting notes with AI", icon: "StickyNote", category: "ai", slug: "meeting-notes", color: "#f97316" },
  { id: "speech-to-text", name: "Speech to Text", description: "Convert speech to text", icon: "Mic", category: "ai", slug: "speech-to-text", isNew: true, color: "#f97316" },
  { id: "text-to-speech", name: "Text to Speech", description: "Convert text to speech", icon: "Volume2", category: "ai", slug: "text-to-speech", isNew: true, color: "#f97316" },
  { id: "ocr-ai", name: "OCR AI", description: "Extract text from images with AI", icon: "Scan", category: "ai", slug: "ocr-ai", color: "#f97316" },

  // Security Tools
  { id: "password-checker", name: "Password Checker", description: "Check password strength", icon: "Shield", category: "security", slug: "password-checker", isPopular: true, color: "#06b6d4" },
  { id: "password-generator-sec", name: "Password Generator", description: "Generate secure passwords", icon: "Key", category: "security", slug: "password-generator-sec", color: "#06b6d4" },
  { id: "file-encrypt", name: "File Encrypt", description: "Encrypt files securely", icon: "Lock", category: "security", slug: "file-encrypt", color: "#06b6d4" },
  { id: "file-decrypt", name: "File Decrypt", description: "Decrypt encrypted files", icon: "Unlock", category: "security", slug: "file-decrypt", color: "#06b6d4" },
  { id: "secure-notes", name: "Secure Notes", description: "Store encrypted notes", icon: "StickyNote", category: "security", slug: "secure-notes", color: "#06b6d4" },
  { id: "otp-generator", name: "OTP Generator", description: "Generate one-time passwords", icon: "Smartphone", category: "security", slug: "otp-generator", color: "#06b6d4" },
  { id: "secret-generator", name: "Secret Generator", description: "Generate secure secrets", icon: "Key", category: "security", slug: "secret-generator", color: "#06b6d4" },

  // Utility Tools
  { id: "qr-scanner", name: "QR Scanner", description: "Scan QR codes with camera", icon: "QrCode", category: "utility", slug: "qr-scanner", isPopular: true, color: "#78716c" },
  { id: "file-converter", name: "File Converter", description: "Convert files between formats", icon: "Repeat", category: "utility", slug: "file-converter", color: "#78716c" },
  { id: "zip-extractor", name: "Zip Extractor", description: "Extract ZIP archives", icon: "FileArchive", category: "utility", slug: "zip-extractor", color: "#78716c" },
  { id: "zip-creator", name: "Zip Creator", description: "Create ZIP archives", icon: "FileArchive", category: "utility", slug: "zip-creator", color: "#78716c" },
  { id: "rename-files", name: "Rename Files", description: "Batch rename files", icon: "FileEdit", category: "utility", slug: "rename-files", color: "#78716c" },
  { id: "duplicate-finder", name: "Duplicate Finder", description: "Find duplicate files", icon: "Files", category: "utility", slug: "duplicate-finder", color: "#78716c" },
  { id: "clipboard-manager", name: "Clipboard Manager", description: "Manage clipboard history", icon: "Clipboard", category: "utility", slug: "clipboard-manager", color: "#78716c" },
  { id: "file-preview", name: "File Preview", description: "Preview any file", icon: "File", category: "utility", slug: "file-preview", color: "#78716c" },
  { id: "download-manager", name: "Download Manager", description: "Manage file downloads", icon: "Download", category: "utility", slug: "download-manager", color: "#78716c" },
]

export const popularTools = tools.filter((t) => t.isPopular)
export const newTools = tools.filter((t) => t.isNew)

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug)
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q)
  )
}

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Alex Chen",
    role: "Product Designer",
    company: "Vercel",
    avatar: "",
    content: "Office Toolkit Pro has completely transformed how I handle daily tasks. The PDF tools alone save me hours every week. It's become an indispensable part of my workflow.",
    rating: 5,
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Software Engineer",
    company: "Stripe",
    avatar: "",
    content: "The developer tools are incredibly polished. The regex tester and JSON formatter are my most-used tools. The attention to detail is remarkable.",
    rating: 5,
  },
  {
    id: "3",
    name: "Marcus Williams",
    role: "Marketing Director",
    company: "Figma",
    avatar: "",
    content: "We use Office Toolkit Pro daily for creating invoices, generating reports, and editing content. The AI features are a game-changer for our marketing team.",
    rating: 5,
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    role: "Freelancer",
    company: "Self-employed",
    avatar: "",
    content: "As a freelancer, I need tools that are both powerful and affordable. Office Toolkit Pro delivers everything I need in one beautiful package. Worth every penny.",
    rating: 5,
  },
  {
    id: "5",
    name: "David Kim",
    role: "CTO",
    company: "Linear",
    avatar: "",
    content: "The quality of this product is outstanding. It feels like a tool built by a dedicated team of designers and engineers. The dark mode is gorgeous.",
    rating: 5,
  },
]
