"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { toast } from "@/components/ui/toast"
import { cn } from "@/lib/utils/cn"
import { Download, Plus, Trash2, Image, Eye, EyeOff } from "lucide-react"

interface Experience { id: string; company: string; role: string; startDate: string; endDate: string; description: string }
interface Education { id: string; school: string; degree: string; startDate: string; endDate: string }
interface Publication { id: string; title: string; publisher: string; date: string; url: string }
interface Project { id: string; name: string; description: string; tech: string; url: string }
interface Volunteer { id: string; organization: string; role: string; startDate: string; endDate: string; description: string }
interface Reference { id: string; name: string; title: string; email: string; phone: string }
interface Certificate { id: string; name: string; issuer: string; date: string }

const TEMPLATES = [
  { id: "modern", name: "Modern", color: "bg-gradient-to-r from-violet-500 to-purple-500" },
  { id: "classic", name: "Classic", color: "bg-gray-900 dark:bg-gray-100" },
  { id: "minimal", name: "Minimal", color: "bg-rose-500" },
]

export function CvBuilder() {
  const [personal, setPersonal] = React.useState({ name: "", email: "", phone: "", location: "", photo: "", title: "" })
  const [summary, setSummary] = React.useState("")
  const [experience, setExperience] = React.useState<Experience[]>([])
  const [education, setEducation] = React.useState<Education[]>([])
  const [skills, setSkills] = React.useState<string[]>([])
  const [skillInput, setSkillInput] = React.useState("")
  const [languages, setLanguages] = React.useState<string[]>([])
  const [langInput, setLangInput] = React.useState("")
  const [certifications, setCertifications] = React.useState<Certificate[]>([])
  const [publications, setPublications] = React.useState<Publication[]>([])
  const [projects, setProjects] = React.useState<Project[]>([])
  const [volunteer, setVolunteer] = React.useState<Volunteer[]>([])
  const [references, setReferences] = React.useState<Reference[]>([])
  const [template, setTemplate] = React.useState("modern")
  const [showPreview, setShowPreview] = React.useState(false)

  const addSkill = () => { if (skillInput.trim() && !skills.includes(skillInput.trim())) { setSkills([...skills, skillInput.trim()]); setSkillInput("") } }
  const removeSkill = (s: string) => setSkills(skills.filter((sk) => sk !== s))
  const addLang = () => { if (langInput.trim() && !languages.includes(langInput.trim())) { setLanguages([...languages, langInput.trim()]); setLangInput("") } }
  const removeLang = (l: string) => setLanguages(languages.filter((lg) => lg !== l))

  const handlePhoto = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) { const r = new FileReader(); r.onload = (ev) => setPersonal({ ...personal, photo: ev.target?.result as string }); r.readAsDataURL(file) }
  }

  const handleDownload = () => {
    if (!personal.name) { toast.error("Please enter your name"); return }
    const w = window.open("", "_blank")
    if (!w) { toast.error("Please allow pop-ups"); return }
    const accent = template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e"
    w.document.write(`
      <html><head><title>CV - ${personal.name}</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1a1a2e; background: ${template === "minimal" ? "#fafafa" : "#fff"}; }
        .header { display: flex; align-items: center; gap: 20px; margin-bottom: 20px; padding-bottom: 20px; border-bottom: 3px solid ${accent}; }
        .header-text h1 { font-size: 32px; margin: 0; color: ${accent}; }
        .section-title { font-size: 15px; font-weight: 700; text-transform: uppercase; letter-spacing: 2px; color: ${accent}; margin-top: 25px; margin-bottom: 10px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; }
        .skill-tag { display: inline-block; background: ${accent}15; color: ${accent}; padding: 3px 10px; border-radius: 12px; font-size: 13px; margin: 2px; }
        .item { margin-bottom: 12px; }
        .item h3 { margin: 0; font-size: 16px; }
        .item .meta { font-size: 13px; color: #64748b; }
        @media print { body { padding: 0; } }
      </style></head><body>
        <div class="header">${personal.photo ? `<img src="${personal.photo}" style="width:90px;height:90px;border-radius:50%;object-fit:cover;border:3px solid ${accent}">` : ""}<div class="header-text"><h1>${personal.name}</h1><p>${personal.title ? personal.title + " | " : ""}${personal.email} | ${personal.phone} | ${personal.location}</p></div></div>
        ${summary ? `<div class="section-title">Professional Summary</div><p style="font-size:14px;color:#475569">${summary}</p>` : ""}
        ${experience.length > 0 ? `<div class="section-title">Experience</div>${experience.map(e => `<div class="item"><h3>${e.role} at ${e.company}</h3><div class="meta">${e.startDate} - ${e.endDate || "Present"}</div><p style="font-size:14px">${e.description}</p></div>`).join("")}` : ""}
        ${education.length > 0 ? `<div class="section-title">Education</div>${education.map(e => `<div class="item"><h3>${e.degree}</h3><div class="meta">${e.school} | ${e.startDate} - ${e.endDate || "Present"}</div></div>`).join("")}` : ""}
        ${projects.length > 0 ? `<div class="section-title">Projects</div>${projects.map(p => `<div class="item"><h3>${p.name}</h3><div class="meta">${p.tech}</div><p style="font-size:14px">${p.description}</p></div>`).join("")}` : ""}
        ${publications.length > 0 ? `<div class="section-title">Publications</div>${publications.map(p => `<div class="item"><h3>${p.title}</h3><div class="meta">${p.publisher} | ${p.date}</div></div>`).join("")}` : ""}
        ${volunteer.length > 0 ? `<div class="section-title">Volunteer Work</div>${volunteer.map(v => `<div class="item"><h3>${v.role} at ${v.organization}</h3><div class="meta">${v.startDate} - ${v.endDate || "Present"}</div><p style="font-size:14px">${v.description}</p></div>`).join("")}` : ""}
        ${skills.length > 0 ? `<div class="section-title">Skills</div><div>${skills.map(s => `<span class="skill-tag">${s}</span>`).join("")}</div>` : ""}
        ${languages.length > 0 ? `<div class="section-title">Languages</div><div>${languages.map(l => `<span class="skill-tag">${l}</span>`).join("")}</div>` : ""}
        ${certifications.length > 0 ? `<div class="section-title">Certifications</div>${certifications.map(c => `<div class="item"><h3>${c.name}</h3><div class="meta">${c.issuer} | ${c.date}</div></div>`).join("")}` : ""}
        ${references.length > 0 ? `<div class="section-title">References</div>${references.map(r => `<div class="item"><h3>${r.name}</h3><div class="meta">${r.title} | ${r.email} | ${r.phone}</div></div>`).join("")}` : ""}
      </body></html>
    `)
    w.document.close()
    setTimeout(() => w.print(), 500)
  }

  return (
    <div className="mx-auto max-w-5xl space-y-8">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="flex items-center justify-between">
        <div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-500/10"><Download className="h-6 w-6 text-violet-500" /></div><div><h1 className="text-2xl font-bold text-foreground">CV Builder</h1><p className="text-sm text-muted-foreground">Create comprehensive CVs</p></div></div>
        <div className="flex items-center gap-2"><Button variant={showPreview ? "primary" : "outline"} size="sm" onClick={() => setShowPreview(!showPreview)}>{showPreview ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</Button><Button variant="primary" size="sm" onClick={handleDownload}><Download className="h-4 w-4" /> Download</Button></div>
      </motion.div>
      <div className="flex flex-wrap gap-2">{TEMPLATES.map((t) => (<button key={t.id} onClick={() => setTemplate(t.id)} className={cn("flex items-center gap-2 rounded-lg border px-4 py-2 text-sm transition-colors", template === t.id ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:border-primary/50")}><div className={cn("h-3 w-3 rounded-full", t.color)} />{t.name}</button>))}</div>

      <AnimatePresence mode="wait">
        {showPreview ? (
          <motion.div key="preview" initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }}>
            <Card className="overflow-hidden p-0">
              <div className={cn("bg-white p-8 dark:bg-gray-950", template === "minimal" && "bg-gray-50 dark:bg-gray-900")}>
                <div className={cn("flex items-start gap-6 border-b pb-6", template === "modern" ? "border-violet-200" : template === "classic" ? "border-gray-300" : "border-rose-200 dark:border-rose-800")}>
                  {personal.photo && <img src={personal.photo} alt="" className="h-24 w-24 rounded-full border-4 object-cover" style={{ borderColor: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }} />}
                  <div><h1 className="text-3xl font-bold" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>{personal.name || "Your Name"}</h1><p className="text-sm text-muted-foreground">{personal.title && <span>{personal.title} | </span>}{personal.email}{personal.phone && ` | ${personal.phone}`}{personal.location && ` | ${personal.location}`}</p></div>
                </div>
                {summary && <div className="mt-4"><h3 className="text-sm font-bold uppercase tracking-wider" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Summary</h3><p className="mt-1 text-sm text-muted-foreground">{summary}</p></div>}
                {experience.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e", borderColor: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Experience</h3>{experience.map(e => <div key={e.id} className="mt-3"><h4 className="font-semibold">{e.role} <span className="font-normal text-muted-foreground">at {e.company}</span></h4><p className="text-xs text-muted-foreground">{e.startDate} - {e.endDate || "Present"}</p><p className="mt-1 text-sm">{e.description}</p></div>)}</div>}
                {education.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Education</h3>{education.map(e => <div key={e.id} className="mt-3"><h4 className="font-semibold">{e.degree}</h4><p className="text-xs text-muted-foreground">{e.school} | {e.startDate} - {e.endDate || "Present"}</p></div>)}</div>}
                {projects.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Projects</h3>{projects.map(p => <div key={p.id} className="mt-3"><h4 className="font-semibold">{p.name}</h4><p className="text-xs text-muted-foreground">{p.tech}</p><p className="mt-1 text-sm">{p.description}</p></div>)}</div>}
                {publications.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Publications</h3>{publications.map(p => <div key={p.id} className="mt-3"><h4 className="font-semibold">{p.title}</h4><p className="text-xs text-muted-foreground">{p.publisher} | {p.date}</p></div>)}</div>}
                {volunteer.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Volunteer Work</h3>{volunteer.map(v => <div key={v.id} className="mt-3"><h4 className="font-semibold">{v.role} <span className="font-normal text-muted-foreground">at {v.organization}</span></h4><p className="text-xs text-muted-foreground">{v.startDate} - {v.endDate || "Present"}</p><p className="mt-1 text-sm">{v.description}</p></div>)}</div>}
                <div className="mt-6 grid grid-cols-2 gap-6">
                  {skills.length > 0 && <div><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Skills</h3><div className="mt-2 flex flex-wrap gap-1.5">{skills.map(s => <span key={s} className="rounded-full bg-muted px-3 py-1 text-xs font-medium text-foreground">{s}</span>)}</div></div>}
                  {languages.length > 0 && <div><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Languages</h3><div className="mt-2 flex flex-wrap gap-1.5">{languages.map(l => <span key={l} className="rounded-full bg-muted px-3 py-1 text-xs font-medium text-foreground">{l}</span>)}</div></div>}
                </div>
                {certifications.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>Certifications</h3>{certifications.map(c => <div key={c.id} className="mt-2"><h4 className="text-sm font-semibold">{c.name}</h4><p className="text-xs text-muted-foreground">{c.issuer} | {c.date}</p></div>)}</div>}
                {references.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold uppercase tracking-wider border-b pb-1" style={{ color: template === "modern" ? "#8b5cf6" : template === "classic" ? "#1e293b" : "#f43f5e" }}>References</h3>{references.map(r => <div key={r.id} className="mt-2"><h4 className="text-sm font-semibold">{r.name}</h4><p className="text-xs text-muted-foreground">{r.title} | {r.email} | {r.phone}</p></div>)}</div>}
              </div>
            </Card>
          </motion.div>
        ) : (
          <motion.div key="edit" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
            <Card><h3 className="mb-4 font-semibold text-foreground">Personal Information</h3>
              <div className="mb-4 flex items-center gap-4">{personal.photo && <img src={personal.photo} alt="" className="h-20 w-20 rounded-full object-cover" />}<label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed border-border px-4 py-2 text-sm text-muted-foreground hover:border-primary/50"><Image className="h-4 w-4" /> Upload Photo<input type="file" accept="image/*" onChange={handlePhoto} className="hidden" /></label>{personal.photo && <Button variant="ghost" size="sm" onClick={() => setPersonal({ ...personal, photo: "" })}>Remove</Button>}</div>
              <div className="grid gap-4 sm:grid-cols-2"><Input label="Full Name" value={personal.name} onChange={(e) => setPersonal({ ...personal, name: e.target.value })} /><Input label="Professional Title" value={personal.title} onChange={(e) => setPersonal({ ...personal, title: e.target.value })} /><Input label="Email" type="email" value={personal.email} onChange={(e) => setPersonal({ ...personal, email: e.target.value })} /><Input label="Phone" value={personal.phone} onChange={(e) => setPersonal({ ...personal, phone: e.target.value })} /><Input label="Location" value={personal.location} onChange={(e) => setPersonal({ ...personal, location: e.target.value })} /></div></Card>
            <Card><h3 className="mb-4 font-semibold text-foreground">Professional Summary</h3><textarea value={summary} onChange={(e) => setSummary(e.target.value)} rows={4} className="w-full resize-y rounded-lg border border-input bg-background p-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2" /></Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">Experience</h3><Button variant="outline" size="sm" onClick={() => setExperience([...experience, { id: crypto.randomUUID(), company: "", role: "", startDate: "", endDate: "", description: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{experience.map((exp, i) => <div key={exp.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setExperience(experience.filter((e) => e.id !== exp.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Company" value={exp.company} onChange={(e) => setExperience(experience.map((ex) => ex.id === exp.id ? { ...ex, company: e.target.value } : ex))} /><Input label="Role" value={exp.role} onChange={(e) => setExperience(experience.map((ex) => ex.id === exp.id ? { ...ex, role: e.target.value } : ex))} /><Input label="Start" type="date" value={exp.startDate} onChange={(e) => setExperience(experience.map((ex) => ex.id === exp.id ? { ...ex, startDate: e.target.value } : ex))} /><Input label="End" type="date" value={exp.endDate} onChange={(e) => setExperience(experience.map((ex) => ex.id === exp.id ? { ...ex, endDate: e.target.value } : ex))} /></div><div className="mt-3"><label className="text-sm font-medium text-foreground">Description</label><textarea value={exp.description} onChange={(e) => setExperience(experience.map((ex) => ex.id === exp.id ? { ...ex, description: e.target.value } : ex))} rows={2} className="mt-1 w-full resize-y rounded-lg border border-input bg-background p-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary/30" /></div></div>)}</Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">Education</h3><Button variant="outline" size="sm" onClick={() => setEducation([...education, { id: crypto.randomUUID(), school: "", degree: "", startDate: "", endDate: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{education.map((edu, i) => <div key={edu.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setEducation(education.filter((e) => e.id !== edu.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="School" value={edu.school} onChange={(e) => setEducation(education.map((ex) => ex.id === edu.id ? { ...ex, school: e.target.value } : ex))} /><Input label="Degree" value={edu.degree} onChange={(e) => setEducation(education.map((ex) => ex.id === edu.id ? { ...ex, degree: e.target.value } : ex))} /><Input label="Start" type="date" value={edu.startDate} onChange={(e) => setEducation(education.map((ex) => ex.id === edu.id ? { ...ex, startDate: e.target.value } : ex))} /><Input label="End" type="date" value={edu.endDate} onChange={(e) => setEducation(education.map((ex) => ex.id === edu.id ? { ...ex, endDate: e.target.value } : ex))} /></div></div>)}</Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">Projects</h3><Button variant="outline" size="sm" onClick={() => setProjects([...projects, { id: crypto.randomUUID(), name: "", description: "", tech: "", url: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{projects.map((p, i) => <div key={p.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setProjects(projects.filter((x) => x.id !== p.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Project Name" value={p.name} onChange={(e) => setProjects(projects.map((x) => x.id === p.id ? { ...x, name: e.target.value } : x))} /><Input label="Technologies" value={p.tech} onChange={(e) => setProjects(projects.map((x) => x.id === p.id ? { ...x, tech: e.target.value } : x))} /><Input label="URL" value={p.url} onChange={(e) => setProjects(projects.map((x) => x.id === p.id ? { ...x, url: e.target.value } : x))} /></div><div className="mt-3"><label className="text-sm font-medium text-foreground">Description</label><textarea value={p.description} onChange={(e) => setProjects(projects.map((x) => x.id === p.id ? { ...x, description: e.target.value } : x))} rows={2} className="mt-1 w-full resize-y rounded-lg border border-input bg-background p-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary/30" /></div></div>)}</Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">Publications</h3><Button variant="outline" size="sm" onClick={() => setPublications([...publications, { id: crypto.randomUUID(), title: "", publisher: "", date: "", url: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{publications.map((pub, i) => <div key={pub.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setPublications(publications.filter((x) => x.id !== pub.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Title" value={pub.title} onChange={(e) => setPublications(publications.map((x) => x.id === pub.id ? { ...x, title: e.target.value } : x))} /><Input label="Publisher" value={pub.publisher} onChange={(e) => setPublications(publications.map((x) => x.id === pub.id ? { ...x, publisher: e.target.value } : x))} /><Input label="Date" type="date" value={pub.date} onChange={(e) => setPublications(publications.map((x) => x.id === pub.id ? { ...x, date: e.target.value } : x))} /><Input label="URL" value={pub.url} onChange={(e) => setPublications(publications.map((x) => x.id === pub.id ? { ...x, url: e.target.value } : x))} /></div></div>)}</Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">Volunteer Work</h3><Button variant="outline" size="sm" onClick={() => setVolunteer([...volunteer, { id: crypto.randomUUID(), organization: "", role: "", startDate: "", endDate: "", description: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{volunteer.map((v, i) => <div key={v.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setVolunteer(volunteer.filter((x) => x.id !== v.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Organization" value={v.organization} onChange={(e) => setVolunteer(volunteer.map((x) => x.id === v.id ? { ...x, organization: e.target.value } : x))} /><Input label="Role" value={v.role} onChange={(e) => setVolunteer(volunteer.map((x) => x.id === v.id ? { ...x, role: e.target.value } : x))} /><Input label="Start" type="date" value={v.startDate} onChange={(e) => setVolunteer(volunteer.map((x) => x.id === v.id ? { ...x, startDate: e.target.value } : x))} /><Input label="End" type="date" value={v.endDate} onChange={(e) => setVolunteer(volunteer.map((x) => x.id === v.id ? { ...x, endDate: e.target.value } : x))} /></div><div className="mt-3"><label className="text-sm font-medium text-foreground">Description</label><textarea value={v.description} onChange={(e) => setVolunteer(volunteer.map((x) => x.id === v.id ? { ...x, description: e.target.value } : x))} rows={2} className="mt-1 w-full resize-y rounded-lg border border-input bg-background p-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary/30" /></div></div>)}</Card>
            <Card><h3 className="mb-4 font-semibold text-foreground">Skills</h3><div className="flex flex-wrap gap-2 mb-3">{skills.map((s) => <span key={s} className="flex items-center gap-1 rounded-full bg-primary/10 px-3 py-1 text-sm text-primary">{s}<button onClick={() => removeSkill(s)} className="hover:text-destructive">&times;</button></span>)}</div><div className="flex gap-2"><Input value={skillInput} onChange={(e) => setSkillInput(e.target.value)} placeholder="Type a skill" onKeyDown={(e) => e.key === "Enter" && addSkill()} /><Button variant="outline" size="sm" onClick={addSkill}>Add</Button></div></Card>
            <Card><h3 className="mb-4 font-semibold text-foreground">Languages</h3><div className="flex flex-wrap gap-2 mb-3">{languages.map((l) => <span key={l} className="flex items-center gap-1 rounded-full bg-muted px-3 py-1 text-sm text-foreground">{l}<button onClick={() => removeLang(l)} className="hover:text-destructive">&times;</button></span>)}</div><div className="flex gap-2"><Input value={langInput} onChange={(e) => setLangInput(e.target.value)} placeholder="Type a language" onKeyDown={(e) => e.key === "Enter" && addLang()} /><Button variant="outline" size="sm" onClick={addLang}>Add</Button></div></Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">Certifications</h3><Button variant="outline" size="sm" onClick={() => setCertifications([...certifications, { id: crypto.randomUUID(), name: "", issuer: "", date: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{certifications.map((c, i) => <div key={c.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setCertifications(certifications.filter((x) => x.id !== c.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Name" value={c.name} onChange={(e) => setCertifications(certifications.map((x) => x.id === c.id ? { ...x, name: e.target.value } : x))} /><Input label="Issuer" value={c.issuer} onChange={(e) => setCertifications(certifications.map((x) => x.id === c.id ? { ...x, issuer: e.target.value } : x))} /><Input label="Date" type="date" value={c.date} onChange={(e) => setCertifications(certifications.map((x) => x.id === c.id ? { ...x, date: e.target.value } : x))} /></div></div>)}</Card>
            <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-foreground">References</h3><Button variant="outline" size="sm" onClick={() => setReferences([...references, { id: crypto.randomUUID(), name: "", title: "", email: "", phone: "" }])}><Plus className="mr-1 h-4 w-4" />Add</Button></div>{references.map((r, i) => <div key={r.id} className="mb-4 rounded-lg border border-border p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-muted-foreground">#{i + 1}</span><motion.button whileHover={{ scale: 1.1 }} onClick={() => setReferences(references.filter((x) => x.id !== r.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></motion.button></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Name" value={r.name} onChange={(e) => setReferences(references.map((x) => x.id === r.id ? { ...x, name: e.target.value } : x))} /><Input label="Title" value={r.title} onChange={(e) => setReferences(references.map((x) => x.id === r.id ? { ...x, title: e.target.value } : x))} /><Input label="Email" type="email" value={r.email} onChange={(e) => setReferences(references.map((x) => x.id === r.id ? { ...x, email: e.target.value } : x))} /><Input label="Phone" value={r.phone} onChange={(e) => setReferences(references.map((x) => x.id === r.id ? { ...x, phone: e.target.value } : x))} /></div></div>)}</Card>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
